# Generated by Django 3.0.4 on 2020-05-06 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.IntegerField()),
                ('icu', models.IntegerField()),
                ('endoscopy', models.IntegerField()),
                ('cardio', models.IntegerField(default=None)),
                ('neuro', models.IntegerField(default=None)),
                ('Doctor_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_ambulance', models.IntegerField()),
                ('patients', models.IntegerField()),
                ('number_of_Rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Rooms')),
            ],
        ),
    ]
