# Generated by Django 3.0.4 on 2020-05-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='recovered_patients',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
